### ISSUE TITLE
recent code dump lost previous PR?

### ISSUE THREAD

**Issue by gquintard** [ip2location/ip2proxy-varnish#3]
Hi,

It looks like that 4de1947b152f7bb8865cd710aa2f568237c8b6b7 erased all changes from https://github.com/ip2location/ip2proxy-varnish/pull/1/ , was that on purpose?

Kin regards,

**Comment by ip2location-com** [comment]
The codes were overwritten when I synced the coding standards from [IP2Location-Varnish](https://github.com/ip2location/IP2Location-Varnish).

Your changes are more up-to-date and tidy! I will revert the changes and populate the standards to IP2Location as well.

**Comment by gquintard** [comment]
That sounds great! I'll open the same kind of PR to IP2Location-Varnish, I just wanted to make sure the changes would stick :-)

Cheers!
